const dummyTransactions = [
  // January
  {
    _id: 1,
    month: "January",
    title: "Samsung Galaxy A12",
    description:
      "A budget-friendly smartphone with 48MP quad camera and 5000mAh battery.",
    category: "Smartphone",
    price: 200,
    sold: true,
  },
  {
    _id: 2,
    month: "January",
    title: "Xiaomi Redmi 10",
    description: "6.5-inch screen with 90Hz refresh rate and 48MP quad camera.",
    category: "Smartphone",
    price: 180,
    sold: false,
  },
  {
    _id: 3,
    month: "January",
    title: "Realme Narzo 30A",
    description:
      "6.5-inch screen, MediaTek Helio G85 processor, and 6000mAh battery.",
    category: "Smartphone",
    price: 150,
    sold: true,
  },
  {
    _id: 4,
    month: "January",
    title: "Vivo Y20",
    description: "13MP triple camera, Snapdragon 460 chipset, 5000mAh battery.",
    category: "Smartphone",
    price: 180,
    sold: false,
  },
  {
    _id: 5,
    month: "January",
    title: "Infinix Hot 10",
    description:
      "6.78-inch screen, MediaTek Helio G70 chipset, and 5000mAh battery.",
    category: "Smartphone",
    price: 170,
    sold: true,
  },
  {
    _id: 6,
    month: "January",
    title: "Oppo A15",
    description:
      "6.52-inch display, MediaTek Helio P35 processor, and 4230mAh battery.",
    category: "Smartphone",
    price: 160,
    sold: false,
  },
  {
    _id: 7,
    month: "January",
    title: "Micromax In 1b",
    description: "6.52-inch screen, MediaTek Helio G35, and 5000mAh battery.",
    category: "Smartphone",
    price: 130,
    sold: true,
  },
  {
    _id: 8,
    month: "January",
    title: "Samsung Galaxy M02",
    description: "5.7-inch screen, 13MP camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 140,
    sold: false,
  },
  {
    _id: 9,
    month: "January",
    title: "Realme C15",
    description:
      "6.5-inch screen, 13MP quad camera, MediaTek Helio G35, 6000mAh battery.",
    category: "Smartphone",
    price: 170,
    sold: true,
  },
  {
    _id: 10,
    month: "January",
    title: "Nokia 3.4",
    description:
      "6.39-inch display, Snapdragon 460 processor, and 4000mAh battery.",
    category: "Smartphone",
    price: 190,
    sold: false,
  },
  {
    _id: 11,
    month: "January",
    title: "Xiaomi Poco M3",
    description: "6.53-inch FHD+, Snapdragon 662, and 6000mAh battery.",
    category: "Smartphone",
    price: 200,
    sold: true,
  },
  {
    _id: 12,
    month: "January",
    title: "Motorola Moto E7 Plus",
    description: "6.5-inch screen, 48MP dual camera, Snapdragon 460 processor.",
    category: "Smartphone",
    price: 210,
    sold: false,
  },

  // February
  {
    _id: 13,
    month: "February",
    title: "Oppo A53",
    description:
      "6.5-inch screen, Snapdragon 460, 13MP triple camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 220,
    sold: true,
  },
  {
    _id: 14,
    month: "February",
    title: "Realme C11",
    description: "6.5-inch screen, MediaTek Helio G35, and 5000mAh battery.",
    category: "Smartphone",
    price: 140,
    sold: false,
  },
  {
    _id: 15,
    month: "February",
    title: "Xiaomi Redmi Note 10",
    description:
      "6.43-inch AMOLED, Snapdragon 678, 48MP camera, and 48-hour battery life.",
    category: "Smartphone",
    price: 240,
    sold: true,
  },
  {
    _id: 16,
    month: "February",
    title: "Vivo Y11",
    description:
      "6.35-inch display, Snapdragon 439, 13MP dual camera, 5000mAh battery.",
    category: "Smartphone",
    price: 190,
    sold: false,
  },
  {
    _id: 17,
    month: "February",
    title: "Samsung Galaxy A02",
    description:
      "6.5-inch screen, MediaTek MT6739, 13MP dual camera, 5000mAh battery.",
    category: "Smartphone",
    price: 150,
    sold: true,
  },
  {
    _id: 18,
    month: "February",
    title: "Micromax In Note 1",
    description: "6.67-inch display, MediaTek Helio G85, and 48MP camera.",
    category: "Smartphone",
    price: 250,
    sold: false,
  },
  {
    _id: 19,
    month: "February",
    title: "Nokia 5.4",
    description:
      "6.39-inch display, Snapdragon 662, 48MP quad camera, and 4000mAh battery.",
    category: "Smartphone",
    price: 270,
    sold: true,
  },
  {
    _id: 20,
    month: "February",
    title: "Xiaomi Poco X3",
    description:
      "6.67-inch FHD+, Snapdragon 732G, 64MP quad camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 280,
    sold: false,
  },
  {
    _id: 21,
    month: "February",
    title: "Realme Narzo 20 Pro",
    description:
      "6.5-inch screen, 48MP quad camera, Snapdragon 720G, and 5000mAh battery.",
    category: "Smartphone",
    price: 270,
    sold: true,
  },
  {
    _id: 22,
    month: "February",
    title: "Vivo Y30",
    description:
      "6.47-inch display, MediaTek Helio P35, 13MP quad camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 230,
    sold: true,
  },
  {
    _id: 23,
    month: "February",
    title: "Samsung Galaxy M02s",
    description:
      "6.5-inch screen, Snapdragon 450, 13MP triple camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 180,
    sold: false,
  },
  {
    _id: 24,
    month: "February",
    title: "Realme 7i",
    description:
      "6.5-inch display, Snapdragon 662, 64MP quad camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 280,
    sold: true,
  },

  // March
  {
    _id: 25,
    month: "March",
    title: "Oppo A73",
    description:
      "6.44-inch AMOLED display, Snapdragon 662, 16MP quad camera, and 4045mAh battery.",
    category: "Smartphone",
    price: 300,
    sold: false,
  },
  {
    _id: 26,
    month: "March",
    title: "Realme X7",
    description:
      "6.4-inch Super AMOLED, MediaTek Dimensity 800U, 64MP camera, and 4310mAh battery.",
    category: "Smartphone",
    price: 320,
    sold: true,
  },
  {
    _id: 27,
    month: "March",
    title: "Xiaomi Mi 10i",
    description:
      "6.67-inch FHD+, Snapdragon 750G, 108MP camera, and 4820mAh battery.",
    category: "Smartphone",
    price: 350,
    sold: false,
  },
  {
    _id: 28,
    month: "March",
    title: "Samsung Galaxy M31",
    description:
      "6.4-inch Super AMOLED, Exynos 9611, 64MP quad camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 330,
    sold: true,
  },
  {
    _id: 29,
    month: "March",
    title: "Motorola Moto G60",
    description:
      "6.8-inch FHD+, Snapdragon 732G, 108MP camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 350,
    sold: false,
  },
  {
    _id: 30,
    month: "March",
    title: "Vivo V20",
    description:
      "6.44-inch AMOLED, Snapdragon 720G, 64MP camera, and 4000mAh battery.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 31,
    month: "March",
    title: "Realme 8 Pro",
    description:
      "6.4-inch Super AMOLED, Snapdragon 720G, 108MP camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 32,
    month: "March",
    title: "Oppo F19 Pro",
    description:
      "6.43-inch AMOLED, MediaTek Helio P95, 48MP camera, and 4310mAh battery.",
    category: "Smartphone",
    price: 340,
    sold: false,
  },
  {
    _id: 33,
    month: "March",
    title: "Realme Narzo 30 Pro",
    description:
      "6.5-inch FHD+, MediaTek Dimensity 800U, 48MP camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 300,
    sold: true,
  },
  {
    _id: 34,
    month: "March",
    title: "Vivo Y51",
    description:
      "6.58-inch screen, Snapdragon 665, 48MP camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 290,
    sold: false,
  },
  {
    _id: 35,
    month: "March",
    title: "Samsung Galaxy A32",
    description:
      "6.4-inch Super AMOLED, MediaTek Helio G80, 64MP camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 320,
    sold: true,
  },

  // April
  {
    _id: 36,
    month: "April",
    title: "Xiaomi Redmi Note 9",
    description:
      "6.53-inch FHD+, MediaTek Helio G85, 48MP quad camera, and 5020mAh battery.",
    category: "Smartphone",
    price: 210,
    sold: false,
  },
  {
    _id: 37,
    month: "April",
    title: "Oppo A15s",
    description:
      "6.52-inch display, MediaTek Helio P35 processor, and 13MP AI triple camera.",
    category: "Smartphone",
    price: 220,
    sold: true,
  },
  {
    _id: 38,
    month: "April",
    title: "Motorola Moto G8 Power Lite",
    description: "6.5-inch screen, MediaTek Helio P35, and 5000mAh battery.",
    category: "Smartphone",
    price: 190,
    sold: false,
  },
  {
    _id: 39,
    month: "April",
    title: "Nokia 3.2",
    description: "6.26-inch screen, Snapdragon 429, and 4000mAh battery.",
    category: "Smartphone",
    price: 160,
    sold: true,
  },
  {
    _id: 40,
    month: "April",
    title: "Samsung Galaxy M21",
    description:
      "6.4-inch Super AMOLED, Exynos 9611, 48MP triple camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 250,
    sold: true,
  },
  {
    _id: 41,
    month: "April",
    title: "Vivo V19 Neo",
    description:
      "6.44-inch AMOLED, Snapdragon 675, 48MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 270,
    sold: false,
  },
  {
    _id: 42,
    month: "April",
    title: "Realme X3",
    description:
      "6.6-inch display, Snapdragon 855+, 64MP quad camera, and 4200mAh battery.",
    category: "Smartphone",
    price: 330,
    sold: true,
  },
  {
    _id: 43,
    month: "April",
    title: "Infinix Zero 8",
    description:
      "6.85-inch display, MediaTek Helio G90T, 48MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 280,
    sold: true,
  },
  {
    _id: 44,
    month: "April",
    title: "Xiaomi Poco F2 Pro",
    description:
      "6.67-inch FHD+, Snapdragon 865, 64MP camera, and 4700mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: false,
  },
  {
    _id: 45,
    month: "April",
    title: "Realme 6 Pro",
    description:
      "6.6-inch display, Snapdragon 720G, 64MP quad camera, and 4300mAh battery.",
    category: "Smartphone",
    price: 300,
    sold: true,
  },
  {
    _id: 46,
    month: "April",
    title: "Samsung Galaxy A71",
    description:
      "6.7-inch Super AMOLED+, Snapdragon 730, 64MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: false,
  },

  // May
  {
    _id: 47,
    month: "May",
    title: "Realme 7 Pro",
    description:
      "6.4-inch Super AMOLED, Snapdragon 720G, 64MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 320,
    sold: true,
  },
  {
    _id: 48,
    month: "May",
    title: "Xiaomi Mi 10T Lite",
    description:
      "6.67-inch FHD+, Snapdragon 750G, 64MP quad camera, and 4820mAh battery.",
    category: "Smartphone",
    price: 350,
    sold: false,
  },
  {
    _id: 49,
    month: "May",
    title: "Samsung Galaxy A52",
    description:
      "6.5-inch Super AMOLED, Snapdragon 720G, 64MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 50,
    month: "May",
    title: "Oppo F19 Pro+",
    description:
      "6.43-inch AMOLED, MediaTek Helio P95, 48MP camera, and 4310mAh battery.",
    category: "Smartphone",
    price: 380,
    sold: false,
  },
  {
    _id: 51,
    month: "May",
    title: "Realme X7 Pro",
    description:
      "6.55-inch Super AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 52,
    month: "May",
    title: "Infinix Zero 8i",
    description:
      "6.85-inch FHD+, MediaTek Helio G90T, 48MP quad camera, and 4500mAh battery.",
    category: "Smartphone",
    price: 290,
    sold: true,
  },
  {
    _id: 53,
    month: "May",
    title: "Motorola Moto G9 Power",
    description:
      "6.8-inch display, Snapdragon 662, 64MP camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 280,
    sold: false,
  },
  {
    _id: 54,
    month: "May",
    title: "Vivo Y73",
    description:
      "6.44-inch AMOLED, MediaTek Helio G95, 64MP camera, and 4000mAh battery.",
    category: "Smartphone",
    price: 340,
    sold: true,
  },
  {
    _id: 55,
    month: "May",
    title: "Realme 8",
    description:
      "6.4-inch Super AMOLED, MediaTek Helio G95, 64MP camera, and 5000mAh battery.",
    category: "Smartphone",
    price: 250,
    sold: false,
  },
  {
    _id: 56,
    month: "May",
    title: "Xiaomi Poco X3 Pro",
    description:
      "6.67-inch FHD+, Snapdragon 860, 48MP quad camera, and 5160mAh battery.",
    category: "Smartphone",
    price: 360,
    sold: true,
  },

  // June
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 57,
    month: "June",
    title: "Oppo Reno 5 Pro",
    description:
      "6.55-inch AMOLED, MediaTek Dimensity 1000+, 64MP camera, and 4350mAh battery.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 1,
    month: "July",
    title: "Samsung Galaxy A32",
    description: "5G smartphone with 6.4-inch AMOLED display and 64MP camera.",
    category: "Smartphone",
    price: 250,
    sold: true,
  },
  {
    _id: 2,
    month: "July",
    title: "Realme Narzo 30 Pro",
    description: "6.5-inch display, 5000mAh battery, and 48MP camera.",
    category: "Smartphone",
    price: 220,
    sold: false,
  },
  {
    _id: 3,
    month: "July",
    title: "Motorola Moto G60",
    description: "120Hz refresh rate, 6GB RAM, and 108MP camera.",
    category: "Smartphone",
    price: 230,
    sold: true,
  },
  {
    _id: 4,
    month: "July",
    title: "Oppo A54",
    description: "Budget phone with 4GB RAM and 5000mAh battery.",
    category: "Smartphone",
    price: 170,
    sold: false,
  },
  {
    _id: 5,
    month: "July",
    title: "Infinix Note 10",
    description: "6.95-inch display, MediaTek Helio G85, and 48MP camera.",
    category: "Smartphone",
    price: 180,
    sold: true,
  },
  {
    _id: 6,
    month: "July",
    title: "Vivo Y73",
    description: "6.44-inch AMOLED display and 64MP triple camera setup.",
    category: "Smartphone",
    price: 290,
    sold: true,
  },
  {
    _id: 7,
    month: "July",
    title: "Xiaomi Redmi Note 10",
    description:
      "6.43-inch AMOLED display, Snapdragon 678 chipset, and 48MP camera.",
    category: "Smartphone",
    price: 210,
    sold: false,
  },
  {
    _id: 8,
    month: "July",
    title: "Poco X3",
    description: "6.67-inch display, 64MP quad camera, and 5160mAh battery.",
    category: "Smartphone",
    price: 240,
    sold: true,
  },
  {
    _id: 9,
    month: "July",
    title: "Samsung Galaxy M12",
    description: "6.5-inch screen, 48MP camera, and 6000mAh battery.",
    category: "Smartphone",
    price: 200,
    sold: true,
  },
  {
    _id: 10,
    month: "July",
    title: "Realme 8 5G",
    description: "5G ready smartphone with a 48MP triple camera setup.",
    category: "Smartphone",
    price: 230,
    sold: false,
  },
  {
    _id: 11,
    month: "July",
    title: "Nokia G50",
    description:
      "5G smartphone with a 48MP triple camera and a large 5000mAh battery.",
    category: "Smartphone",
    price: 180,
    sold: true,
  },
  {
    _id: 12,
    month: "July",
    title: "Lava Agni 5G",
    description: "6.78-inch FHD+ display, 5G connectivity, and 64MP camera.",
    category: "Smartphone",
    price: 260,
    sold: true,
  },

  // August
  {
    _id: 13,
    month: "August",
    title: "OnePlus Nord CE 5G",
    description: "6.43-inch AMOLED, Snapdragon 750G, and 64MP camera.",
    category: "Smartphone",
    price: 300,
    sold: true,
  },
  {
    _id: 14,
    month: "August",
    title: "Xiaomi Mi 11 Lite",
    description: "Ultra-slim design, 64MP camera, and 33W fast charging.",
    category: "Smartphone",
    price: 280,
    sold: false,
  },
  {
    _id: 15,
    month: "August",
    title: "Vivo V21e",
    description: "6.44-inch AMOLED display and 44MP dual selfie camera.",
    category: "Smartphone",
    price: 240,
    sold: true,
  },
  {
    _id: 16,
    month: "August",
    title: "Samsung Galaxy M32",
    description: "6.4-inch FHD+ AMOLED display and 64MP quad camera.",
    category: "Smartphone",
    price: 250,
    sold: true,
  },
  {
    _id: 17,
    month: "August",
    title: "Infinix Zero 8",
    description: "90Hz refresh rate, 64MP quad camera, and 33W fast charging.",
    category: "Smartphone",
    price: 230,
    sold: false,
  },
  {
    _id: 18,
    month: "August",
    title: "Realme X7",
    description: "5G-enabled with 120Hz AMOLED display and 64MP camera.",
    category: "Smartphone",
    price: 320,
    sold: true,
  },
  {
    _id: 19,
    month: "August",
    title: "Oppo F19 Pro+",
    description:
      "5G smartphone with a 48MP quad-camera setup and fast charging.",
    category: "Smartphone",
    price: 290,
    sold: true,
  },
  {
    _id: 20,
    month: "August",
    title: "Lava Z6",
    description: "6.5-inch display with 64MP quad camera and 5000mAh battery.",
    category: "Smartphone",
    price: 210,
    sold: true,
  },
  {
    _id: 21,
    month: "August",
    title: "Poco M3 Pro 5G",
    description: "6.5-inch display, Dimensity 700, and 48MP camera.",
    category: "Smartphone",
    price: 200,
    sold: false,
  },
  {
    _id: 22,
    month: "August",
    title: "Nokia 5.4",
    description:
      "6.39-inch display with Snapdragon 662 chipset and 48MP quad camera.",
    category: "Smartphone",
    price: 220,
    sold: true,
  },
  {
    _id: 23,
    month: "August",
    title: "Motorola Edge 20",
    description: "6.7-inch OLED display, Snapdragon 778G, and 108MP camera.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 24,
    month: "August",
    title: "Samsung Galaxy A52s",
    description: "Super AMOLED 120Hz, Snapdragon 778G, and 64MP camera.",
    category: "Smartphone",
    price: 370,
    sold: false,
  },

  // September
  {
    _id: 25,
    month: "September",
    title: "Redmi Note 11 Pro",
    description: "6.67-inch AMOLED, Snapdragon 695, and 108MP camera.",
    category: "Smartphone",
    price: 310,
    sold: true,
  },
  {
    _id: 26,
    month: "September",
    title: "Samsung Galaxy A72",
    description: "6.7-inch Super AMOLED, Snapdragon 720G, and 64MP camera.",
    category: "Smartphone",
    price: 430,
    sold: false,
  },
  {
    _id: 27,
    month: "September",
    title: "OnePlus Nord 2",
    description: "6.43-inch AMOLED, Dimensity 1200, and 50MP camera.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 28,
    month: "September",
    title: "Realme 9 Pro",
    description: "6.6-inch display, Snapdragon 695, and 64MP camera.",
    category: "Smartphone",
    price: 330,
    sold: true,
  },
  {
    _id: 29,
    month: "September",
    title: "Vivo V21 5G",
    description: "6.44-inch AMOLED, Dimensity 800U, and 44MP camera.",
    category: "Smartphone",
    price: 320,
    sold: true,
  },
  {
    _id: 30,
    month: "September",
    title: "Motorola Moto G60s",
    description: "6.8-inch display, Snapdragon 732G, and 64MP camera.",
    category: "Smartphone",
    price: 290,
    sold: false,
  },
  {
    _id: 31,
    month: "September",
    title: "Oppo Reno 6",
    description: "6.43-inch AMOLED, MediaTek Dimensity 900, and 64MP camera.",
    category: "Smartphone",
    price: 380,
    sold: true,
  },
  {
    _id: 32,
    month: "September",
    title: "Poco F3",
    description: "6.67-inch AMOLED, Snapdragon 870, and 48MP camera.",
    category: "Smartphone",
    price: 460,
    sold: false,
  },
  {
    _id: 33,
    month: "September",
    title: "Xiaomi Mi 11X Pro",
    description: "6.67-inch AMOLED, Snapdragon 888, and 108MP camera.",
    category: "Smartphone",
    price: 500,
    sold: true,
  },
  {
    _id: 34,
    month: "September",
    title: "Realme GT Master Edition",
    description: "6.43-inch Super AMOLED, Snapdragon 778G, and 64MP camera.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 35,
    month: "September",
    title: "Nokia 8.3 5G",
    description:
      "6.81-inch Full HD+ display, Snapdragon 765G, and 64MP camera.",
    category: "Smartphone",
    price: 420,
    sold: false,
  },

  // October
  {
    _id: 36,
    month: "October",
    title: "Oppo A15",
    description:
      "6.52-inch HD+ display, 13MP triple camera setup, and 4230mAh battery.",
    category: "Smartphone",
    price: 150,
    sold: true,
  },
  {
    _id: 37,
    month: "October",
    title: "Xiaomi Poco X3",
    description: "6.67-inch display, Snapdragon 732G, and 64MP camera.",
    category: "Smartphone",
    price: 220,
    sold: false,
  },
  {
    _id: 38,
    month: "October",
    title: "Samsung Galaxy M51",
    description: "6.7-inch AMOLED, Snapdragon 730G, and 64MP quad camera.",
    category: "Smartphone",
    price: 330,
    sold: true,
  },
  {
    _id: 39,
    month: "October",
    title: "Realme Narzo 30",
    description: "6.5-inch display, MediaTek Helio G95, and 48MP camera.",
    category: "Smartphone",
    price: 200,
    sold: true,
  },
  {
    _id: 40,
    month: "October",
    title: "Vivo Y31s",
    description: "6.58-inch FHD+ display, Snapdragon 480, and 13MP camera.",
    category: "Smartphone",
    price: 220,
    sold: false,
  },
  {
    _id: 41,
    month: "October",
    title: "Xiaomi Redmi Note 10 Pro",
    description: "6.67-inch AMOLED, Snapdragon 732G, and 108MP camera.",
    category: "Smartphone",
    price: 290,
    sold: true,
  },
  {
    _id: 42,
    month: "October",
    title: "Infinix Zero 8i",
    description: "6.85-inch display, 48MP quad camera, and 33W fast charging.",
    category: "Smartphone",
    price: 250,
    sold: false,
  },
  {
    _id: 43,
    month: "October",
    title: "Samsung Galaxy A32",
    description: "6.4-inch AMOLED, Helio G85, and 64MP camera.",
    category: "Smartphone",
    price: 230,
    sold: true,
  },
  {
    _id: 44,
    month: "October",
    title: "Realme X7 Pro",
    description: "6.55-inch AMOLED, MediaTek Dimensity 1000+, and 64MP camera.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 45,
    month: "October",
    title: "Motorola Edge Plus",
    description: "6.7-inch OLED, Snapdragon 865, and 108MP camera.",
    category: "Smartphone",
    price: 450,
    sold: false,
  },

  // November
  {
    _id: 46,
    month: "November",
    title: "Oppo Reno 6 Pro",
    description: "6.55-inch AMOLED, MediaTek Dimensity 1200, and 64MP camera.",
    category: "Smartphone",
    price: 380,
    sold: true,
  },
  {
    _id: 47,
    month: "November",
    title: "OnePlus 9R",
    description: "6.55-inch AMOLED, Snapdragon 870, and 48MP camera.",
    category: "Smartphone",
    price: 450,
    sold: false,
  },
  {
    _id: 48,
    month: "November",
    title: "Vivo V21e",
    description:
      "6.44-inch AMOLED, MediaTek Dimensity 700, and 44MP selfie camera.",
    category: "Smartphone",
    price: 240,
    sold: true,
  },
  {
    _id: 49,
    month: "November",
    title: "Realme 8 Pro",
    description: "6.4-inch AMOLED, Snapdragon 720G, and 108MP camera.",
    category: "Smartphone",
    price: 290,
    sold: true,
  },
  {
    _id: 50,
    month: "November",
    title: "Motorola Moto G100",
    description: "6.7-inch FHD+ display, Snapdragon 870, and 64MP camera.",
    category: "Smartphone",
    price: 400,
    sold: true,
  },
  {
    _id: 51,
    month: "November",
    title: "Samsung Galaxy A72",
    description: "6.7-inch Super AMOLED, Snapdragon 720G, and 64MP camera.",
    category: "Smartphone",
    price: 440,
    sold: false,
  },
  {
    _id: 52,
    month: "November",
    title: "Redmi Note 11",
    description: "6.43-inch AMOLED, Snapdragon 680, and 50MP camera.",
    category: "Smartphone",
    price: 220,
    sold: true,
  },
  {
    _id: 53,
    month: "November",
    title: "Xiaomi Poco X3 Pro",
    description: "6.67-inch LCD, Snapdragon 860, and 48MP camera.",
    category: "Smartphone",
    price: 250,
    sold: false,
  },
  {
    _id: 54,
    month: "November",
    title: "Realme Narzo 30 Pro",
    description: "6.5-inch display, MediaTek Helio G95, and 48MP camera.",
    category: "Smartphone",
    price: 230,
    sold: true,
  },
  {
    _id: 55,
    month: "November",
    title: "Infinix Zero 8",
    description: "6.85-inch display, 64MP quad camera, and 33W fast charging.",
    category: "Smartphone",
    price: 270,
    sold: true,
  },

  // December
  {
    _id: 56,
    month: "December",
    title: "Samsung Galaxy A52",
    description: "6.5-inch Super AMOLED, Snapdragon 720G, and 64MP camera.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 57,
    month: "December",
    title: "OnePlus 8T",
    description: "6.55-inch Fluid AMOLED, Snapdragon 865, and 48MP camera.",
    category: "Smartphone",
    price: 400,
    sold: false,
  },
  {
    _id: 58,
    month: "December",
    title: "Xiaomi Redmi Note 10 Pro",
    description: "6.67-inch AMOLED, Snapdragon 732G, and 108MP camera.",
    category: "Smartphone",
    price: 270,
    sold: true,
  },
  {
    _id: 59,
    month: "December",
    title: "Realme GT",
    description: "6.43-inch Super AMOLED, Snapdragon 870, and 64MP camera.",
    category: "Smartphone",
    price: 430,
    sold: false,
  },
  {
    _id: 60,
    month: "December",
    title: "Poco F3 GT",
    description: "6.67-inch AMOLED, MediaTek Dimensity 1200, and 64MP camera.",
    category: "Smartphone",
    price: 350,
    sold: true,
  },
  {
    _id: 61,
    month: "December",
    title: "Vivo X60 Pro",
    description: "6.56-inch AMOLED, Snapdragon 870, and 48MP camera.",
    category: "Smartphone",
    price: 500,
    sold: true,
  },
  {
    _id: 62,
    month: "December",
    title: "Oppo F19 Pro",
    description: "6.43-inch AMOLED, MediaTek Helio P95, and 48MP camera.",
    category: "Smartphone",
    price: 320,
    sold: false,
  },
  {
    _id: 63,
    month: "December",
    title: "Infinix Zero 8i",
    description: "6.85-inch display, 48MP quad camera, and 33W fast charging.",
    category: "Smartphone",
    price: 250,
    sold: true,
  },
  {
    _id: 64,
    month: "December",
    title: "Nokia 5.4",
    description: "6.39-inch display, Snapdragon 662, and 48MP quad camera.",
    category: "Smartphone",
    price: 230,
    sold: true,
  },
  {
    _id: 65,
    month: "December",
    title: "Realme 8 5G",
    description: "6.5-inch display, Dimensity 700, and 48MP camera.",
    category: "Smartphone",
    price: 270,
    sold: false,
  },
];

module.exports = { dummyTransactions };
