const dummyTransactions = [
  { _id: 1, month: "January", title: "Product A", price: 150, sold: true },
  { _id: 2, month: "January", title: "Product B", price: 90, sold: false },
  { _id: 3, month: "February", title: "Product C", price: 200, sold: true },
  { _id: 4, month: "February", title: "Product D", price: 250, sold: true },
  { _id: 5, month: "March", title: "Product E", price: 350, sold: false },
  { _id: 6, month: "March", title: "Product F", price: 400, sold: true },
  { _id: 7, month: "March", title: "Product G", price: 120, sold: true },
  { _id: 8, month: "March", title: "Product H", price: 180, sold: false },
  { _id: 9, month: "January", title: "Product I", price: 210, sold: true },
  { _id: 10, month: "January", title: "Product J", price: 250, sold: false },
  { _id: 11, month: "February", title: "Product K", price: 190, sold: true },
  { _id: 12, month: "February", title: "Product L", price: 350, sold: true },
  { _id: 13, month: "March", title: "Product M", price: 400, sold: false },
  { _id: 14, month: "March", title: "Product N", price: 450, sold: true },
  { _id: 15, month: "March", title: "Product O", price: 130, sold: true },
  { _id: 16, month: "April", title: "Product P", price: 200, sold: false },
  { _id: 17, month: "April", title: "Product Q", price: 500, sold: true },
  { _id: 18, month: "April", title: "Product R", price: 150, sold: true },
  { _id: 19, month: "May", title: "Product S", price: 300, sold: false },
  { _id: 20, month: "May", title: "Product T", price: 370, sold: true },
  { _id: 21, month: "June", title: "Product U", price: 220, sold: true },
  { _id: 22, month: "June", title: "Product V", price: 310, sold: false },
  { _id: 23, month: "July", title: "Product W", price: 180, sold: true },
  { _id: 24, month: "July", title: "Product X", price: 140, sold: true },
  { _id: 25, month: "August", title: "Product Y", price: 210, sold: true },
  { _id: 26, month: "August", title: "Product Z", price: 150, sold: false },
  { _id: 27, month: "September", title: "Product AA", price: 250, sold: true },
  { _id: 28, month: "September", title: "Product BB", price: 180, sold: true },
  { _id: 29, month: "October", title: "Product CC", price: 300, sold: false },
  { _id: 30, month: "October", title: "Product DD", price: 350, sold: true },
  { _id: 31, month: "November", title: "Product EE", price: 420, sold: true },
  { _id: 32, month: "November", title: "Product FF", price: 500, sold: false },
  { _id: 33, month: "December", title: "Product GG", price: 390, sold: true },
  { _id: 34, month: "December", title: "Product HH", price: 450, sold: false },
  { _id: 35, month: "January", title: "Product II", price: 120, sold: true },
  { _id: 36, month: "January", title: "Product JJ", price: 270, sold: false },
  { _id: 37, month: "February", title: "Product KK", price: 200, sold: true },
  { _id: 38, month: "February", title: "Product LL", price: 220, sold: true },
  { _id: 39, month: "March", title: "Product MM", price: 340, sold: false },
  { _id: 40, month: "March", title: "Product NN", price: 260, sold: true },
  { _id: 41, month: "April", title: "Product OO", price: 180, sold: true },
  { _id: 42, month: "April", title: "Product PP", price: 210, sold: false },
  { _id: 43, month: "May", title: "Product QQ", price: 230, sold: true },
  { _id: 44, month: "May", title: "Product RR", price: 300, sold: true },
  { _id: 45, month: "June", title: "Product SS", price: 350, sold: false },
  { _id: 46, month: "June", title: "Product TT", price: 400, sold: true },
  { _id: 47, month: "July", title: "Product UU", price: 120, sold: true },
  { _id: 48, month: "July", title: "Product VV", price: 180, sold: false },
  { _id: 49, month: "August", title: "Product WW", price: 230, sold: true },
  { _id: 50, month: "August", title: "Product XX", price: 320, sold: false },
  { _id: 51, month: "September", title: "Product YY", price: 290, sold: true },
  { _id: 52, month: "September", title: "Product ZZ", price: 260, sold: true },
  { _id: 53, month: "October", title: "Product AAA", price: 370, sold: true },
  { _id: 54, month: "October", title: "Product BBB", price: 420, sold: false },
  { _id: 55, month: "November", title: "Product CCC", price: 500, sold: true },
  { _id: 56, month: "November", title: "Product DDD", price: 450, sold: false },
  { _id: 57, month: "December", title: "Product EEE", price: 380, sold: true },
  { _id: 58, month: "December", title: "Product FFF", price: 400, sold: true },
  { _id: 59, month: "January", title: "Product GGG", price: 350, sold: true },
  { _id: 60, month: "January", title: "Product HHH", price: 240, sold: false },
  { _id: 61, month: "February", title: "Product III", price: 210, sold: true },
  { _id: 62, month: "February", title: "Product JJJ", price: 220, sold: true },
  { _id: 63, month: "March", title: "Product KKK", price: 240, sold: false },
  { _id: 64, month: "March", title: "Product LLL", price: 250, sold: true },
  { _id: 65, month: "April", title: "Product MMM", price: 270, sold: true },
  { _id: 66, month: "April", title: "Product NNN", price: 300, sold: false },
  { _id: 67, month: "May", title: "Product OOO", price: 350, sold: true },
  { _id: 68, month: "May", title: "Product PPP", price: 400, sold: false },
  { _id: 69, month: "June", title: "Product QQQ", price: 450, sold: true },
  { _id: 70, month: "June", title: "Product RRR", price: 500, sold: false },
  { _id: 71, month: "July", title: "Product SSS", price: 150, sold: true },
  { _id: 72, month: "July", title: "Product TTT", price: 180, sold: false },
  { _id: 73, month: "August", title: "Product UUU", price: 220, sold: true },
  { _id: 74, month: "August", title: "Product VVV", price: 240, sold: false },
  { _id: 75, month: "September", title: "Product WWW", price: 300, sold: true },
  {
    _id: 76,
    month: "September",
    title: "Product XXX",
    price: 350,
    sold: false,
  },
  { _id: 77, month: "October", title: "Product YYY", price: 400, sold: true },
  { _id: 78, month: "October", title: "Product ZZZ", price: 450, sold: false },
  { _id: 79, month: "November", title: "Product AAAA", price: 500, sold: true },
  {
    _id: 80,
    month: "November",
    title: "Product BBBB",
    price: 450,
    sold: false,
  },
  { _id: 81, month: "December", title: "Product CCCC", price: 300, sold: true },
  {
    _id: 82,
    month: "December",
    title: "Product DDDD",
    price: 350,
    sold: false,
  },
  { _id: 83, month: "January", title: "Product EEEE", price: 380, sold: true },
  { _id: 84, month: "January", title: "Product FFFF", price: 420, sold: false },
  { _id: 85, month: "February", title: "Product GGGG", price: 400, sold: true },
  { _id: 86, month: "February", title: "Product HHHH", price: 350, sold: true },
  { _id: 87, month: "March", title: "Product IIII", price: 420, sold: false },
  { _id: 88, month: "March", title: "Product JJJJ", price: 450, sold: true },
  { _id: 89, month: "April", title: "Product KKKK", price: 470, sold: true },
  { _id: 90, month: "April", title: "Product LLLL", price: 500, sold: false },
  { _id: 91, month: "May", title: "Product MMMM", price: 500, sold: true },
  { _id: 92, month: "May", title: "Product NNNN", price: 480, sold: false },
  { _id: 93, month: "June", title: "Product OOOO", price: 520, sold: true },
  { _id: 94, month: "June", title: "Product PPPP", price: 550, sold: false },
  { _id: 95, month: "July", title: "Product QQQQ", price: 580, sold: true },
  { _id: 96, month: "July", title: "Product RRRR", price: 600, sold: false },
  { _id: 97, month: "August", title: "Product SSSS", price: 650, sold: true },
  { _id: 98, month: "August", title: "Product TTTT", price: 700, sold: false },
  {
    _id: 99,
    month: "September",
    title: "Product UUUU",
    price: 750,
    sold: true,
  },
  {
    _id: 100,
    month: "September",
    title: "Product VVVV",
    price: 800,
    sold: false,
  },
];
